FROM tensorflow/tensorflow:2.20.0

WORKDIR /app/src
COPY ./src /app/src
COPY ./requirements.txt /app/requirements.txt
COPY ./models/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5 /app/models/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5

ENV TF_XLA_FLAGS=--tf_xla_cpu_global_jit

RUN mkdir -p /root/.keras/models && mv /app/models/* /root/.keras/models/

RUN pip install --upgrade pip
# COPY ./python3.11/* /usr/local/lib/python3.11/
RUN pip install --ignore-installed -r /app/requirements.txt -i https://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com

RUN mkdir -p /tmp/search-images


#CMD gunicorn --bind 0.0.0.0:5000 -w 2 app:app --preload

CMD ["python", "app.py"]

# docker build   -t   milvusbootcamp/pic-search-webserver:2.20.0  .